name: build-steer_infantry_cs

on:
  push:
    branches:
      - target/steer_infantry_cs

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ref: ${{ github.sha }}
      - uses: ./.github/actions/build-target
        with:
          target: steer_infantry_cs
          build_type: ${{ env.BUILD_TYPE }}

