name: build-all-targets

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-dart_rack:
    uses: ./.github/workflows/build-dart_rack.yml

  build-drone_gb:
    uses: ./.github/workflows/build-drone_gb.yml

  build-old_sentry:
    uses: ./.github/workflows/build-old_sentry.yml

  build-omni_target:
    uses: ./.github/workflows/build-omni_target.yml

  build-steer_infantry_cs:
    uses: ./.github/workflows/build-steer_infantry_cs.yml

  build-steer_infantry_gb:
    uses: ./.github/workflows/build-steer_infantry_gb.yml

