name: build-drone_gb

on:
  push:
    branches:
      - target/drone_gb

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
          ref: ${{ github.sha }}
      - uses: ./.github/actions/build-target
        with:
          target: drone_gb
          build_type: ${{ env.BUILD_TYPE }}

